version: '3.7'
services:
  mongodb_container:
    image: 'mongo'
    container_name: 'customer-list-db'
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
